version: 2
jobs:
  test:
    docker:
      - image: circleci/clojure:lein-2.8.1
    working_directory: ~/work
    steps:
      - checkout
      - restore_cache:
          key: v1-{{checksum "project.clj"}}
      - run: lein deps
      - save_cache:
          key: v1-{{checksum "project.clj"}}
          paths:
            - ~/.m2
      - run: lein eftest

  lint:
    docker:
      - image: circleci/clojure:lein-2.8.1
    working_directory: ~/work
    steps:
      - checkout
      - run: |
          if [ ! -z "$CIRCLE_PULL_REQUEST" ]; then
            if [ ! -f "RELEASE.md" ]; then
              echo "For a pull request to be merged, a RELEASE.md is needed!"
              exit 1
            fi
          fi

  release:
    docker:
      - image: circleci/clojure:lein-2.8.1
    working_directory: ~/work
    steps:
      - checkout
      - restore_cache:
          key: v1-{{checksum "project.clj"}}
      - run: |
          git config user.email "miikka.koskinen+ci@iki.fi"
          git config user.name  "Build automation"
      - run: |
          ./scripts/decrypt-secrets.sh "$SECRETS_PASSPHRASE"
          gpg --import secrets/signing-key.asc
          mkdir -p ~/.lein && cp secrets/profiles.clj ~/.lein/
      - add_ssh_keys:
          fingerprints:
            - "fb:50:55:46:05:d2:79:aa:67:77:da:9f:c1:50:ee:b0"
      - run: ./scripts/release.sh

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - lint:
          filters:
            branches:
              ignore:
                - master
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
